BIN  = ./dist
SRC  = ./src
INC  = ./include
TEST = ./test


compile: 
	gcc $(SRC)/firstDataStructure.c  $(TEST)/test.c -o $(BIN)/firstDataStructure
	
run:
	./$(BIN)/firstDataStructure

clean: 
	rm ./$(BIN)/*.exe



