BIN  = ./dist
SRC  = ./src
INC  = ./include


compile: 
	gcc $(SRC)/linearList.c -o $(BIN)/linearList
	gcc $(SRC)/linearListSecond.c -o $(BIN)/linearListSecond
	
run:
	./$(BIN)/linearList
	./$(BIN)/linearListSecond

clean: 
	rm ./$(BIN)/*.exe




